quarkus:
  datasource:
    db-kind: h2
    username: sa
    password: password
    jdbc:
      url: jdbc:h2:file:./_data/dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
  flyway:
    migrate-at-start: true
